displayName: TLSGuard
type: middleware
iconPath: .assets/icon.png

import: github.com/hhftechnology/tlsguard

summary: 'A comprehensive authentication plugin for Traefik that combines certificate-based user authentication with IP whitelisting and rule-based access control'

testData:
  # User authentication based on certificates
  usernameHeader: "User"
  users:
    alice: alice
    bob1: bob
    charlie@example.org: charlie
  
  # Optional IP whitelisting and rules
  refreshInterval: 30m
  requestHeaders:
    X-Cert-Mail: "[[.Cert.Subject.CommonName]]@domain.tld"
  rules:
  - type: ipRange
    addInterface: true
    ranges:
    - 127.0.0.1/8
    - 192.168.0.1/16